HASHED_FILE_EXTENSION = "_hash"
DEFAULT_COLUMNS_TO_HASH = ["ssn"]
DEFAULT_CSV_DELIMiTER = ","
DEFAULT_FILES_TO_HASH = ["*"]
DEFAULT_WORKING_DIRECTORY = "."
DEFAULT_CSV_ENCODING = "utf_8"
SESSION_CACHE = "session_cache.bin"
TEST_CONFIG_FILE_PATH = "tests/utils/config_example.txt"

